id: PA909406C
initial_creation_type: input
source_metadata:
  title: 'Asaṅga/Maitreya: Mahāyānasūtrālaṃkāra'
  language: zh
  volumes:
    d37e3ccfc3534b4c8d824f2ec24cc970:
      title: CI_Verses 21-40
      base_file: CI_Verses 21-40.txt
      work_id: WCDC1454E
    c74a62ea4c434803bff5f5c21fd4fe78:
      title: Chapter II
      base_file: Chapter II.txt
      work_id: WC5626E16
    1689c35f54e74865975742348ca48390:
      title: Chapter III
      base_file: Chapter III.txt
      work_id: W0A810F74
    0bb0854958af4bc4a0743fc5711d4f1e:
      title: Chapter IV
      base_file: Chapter IV.txt
      work_id: WA128DA7E
    1c1147b4d7874ac4a84b489cb637f6a4:
      title: Chapter IX
      base_file: Chapter IX.txt
      work_id: WEA4675F4
    52aa00d4c64e438a8ec82324c12d916b:
      title: Chapter V
      base_file: Chapter V.txt
      work_id: W049C9A6E
    d0ce8e47c7294352a7c09627370d8fe6:
      title: Chapter VI
      base_file: Chapter VI.txt
      work_id: W88AA81E3
    19c07336c3e74e37b0f99078cf918cf5:
      title: Chapter VII
      base_file: Chapter VII.txt
      work_id: W5AEC4744
    ad116eb97daf428db90726ce14ac10ad:
      title: Chapter VIII
      base_file: Chapter VIII.txt
      work_id: WE65DA6A2
    869640e0e29d4ec88acc42d726ff8da3:
      title: Chapter X
      base_file: Chapter X.txt
      work_id: W76E0B281
    debb7dc185ed40ba8a320e16af90092a:
      title: Chapter XI
      base_file: Chapter XI.txt
      work_id: W37628167
    7f5171e54fee49a596fe0af8b95c9d1f:
      title: Chapter XII
      base_file: Chapter XII.txt
      work_id: WD9B26295
    22d14e29308a4c32ac42fc2a714b12e6:
      title: Chapter XIII
      base_file: Chapter XIII.txt
      work_id: W9E5FB3BE
    eaff6776526241e29a49238333f8667c:
      title: Chapter XIV
      base_file: Chapter XIV.txt
      work_id: W6579626F
    e19d059f5d1440879cc183d76fb88684:
      title: Chapter XIX
      base_file: Chapter XIX.txt
      work_id: W99F9593D
    4ec3525039a24536b5f9b0cb328104c5:
      title: Chapter XV
      base_file: Chapter XV.txt
      work_id: WF4A29C49
    77ce6eaa81994153afc737193f2d6171:
      title: Chapter XVI
      base_file: Chapter XVI.txt
      work_id: W293330CF
    0fb4d3daf8064d7687d6643f7a385a7a:
      title: Chapter XVII
      base_file: Chapter XVII.txt
      work_id: W90109957
    2c06ce02cee0466286489636fe7fbf3e:
      title: Chapter XVIII
      base_file: Chapter XVIII.txt
      work_id: W0F207E0F
    1921f70d121f47e7918ca1651db4077e:
      title: Chapter XX-XXI
      base_file: Chapter XX-XXI.txt
      work_id: W139F02BB
    2e627500c4fa48a0bb2b5607d8691214:
      title: Colophon
      base_file: Colophon.txt
      work_id: W5E63425B
    5a7d18f36354488f9478c05e377add6d:
      title: Preface
      base_file: Preface.txt
      work_id: W542ACBE3
    a9f965e1c2da44e5b452986b612101a3:
      title: Title
      base_file: Title.txt
      work_id: W988863EF
  chapter_to_tile:
    CI: Chapter I
created_at: '2022-03-01T23:01:13.790431'
last_modified_at: '2022-03-01T23:01:13.790441'
